### ISSUE TITLE
Request: Add functionality to scroll using mouse wheel/trackpad equivalent on OSX version.

### ISSUE THREAD

**Issue by G-R-O-U-C-H-O** [mkulesh/onpc#322]
Currently to scroll, one needs to move the mouse pointer to the left, wait for the scroll bar to appear, click and hold on it, and drag.

Would be good to have normal 'mouse wheel' scrolling behaviour. :-)

Thank you.

**Comment by mkulesh** [comment]
Hi! I think you use the iOS version of the app on your Apple Silicon Mac, correct? I have no experience with such a  setup, but I am sure that a build for a mobile platform will work on the desktop platform with some limitations like missing 'mouse wheel' scrolling. 

To overcome these limitations, I also have the native macOS build. Could you please install and try this build? There are two possibilities to install it:
- on your mac, install TestFlight from App Store and than follow the public link: https://testflight.apple.com/join/oV5j2iMh
- manually download macOS DMG file (MusicControl-v2.14.0-macos.dmg.zip) from here: https://onedrive.live.com/?authkey=%21AMDFl6N3ncDowMg&cid=85210F986F87ACDD&id=85210F986F87ACDD%21465&parId=85210F986F87ACDD%21118&o=OneUp
unzip it, open DMG and drag the MusicControl app into Application

Does this build works as desired?

**Comment by G-R-O-U-C-H-O** [comment]
Hello Mikhail.

Thank you for your reply.

I did not know that the app was iOS-native. I downloaded it from the ‘Mac apps’ section.

￼

With regards to the revised file you linked to in your email, I downloaded and ran the file from the DMG.

The behaviour has not changed as far as I can make out (I used the settings section to try it out).

To scroll down from the top of the settings to the bottom, I have to move the cursor to the right, wait for the scroll bar to appear, and click and drag that bar down.
￼
Not related - but just so you know, the app is working fine with the new Onkyo TX-8470 for me.

Thank you again.

Best,
Malcolm

**Comment by mkulesh** [comment]
Hello! This is really strange!

Take a look on the screen recording below:
https://github.com/user-attachments/assets/875c7677-fe1f-45c8-8b16-30bf07b5d256

This is recorded on Intel mac-mini 2018 with Sonoma 14.6.1. As you can see, the scrolling using mouse wheel works in shortcuts, navigation menu, media list. On the same way it works in the app settings.

The behavior you describe looks like iOS app behavior and I have no idea hwy the macOS version demonstrates the same behavior in your case. Which mac and macOS do you have? 

In the application settings, do you have the item "Use USB-RI interface" in the "Advanced" parameter group?

Could you please do following:
- Open Settings from the application menu
- Activate the "Developer options" on the end of the settings list
- Close app
- Open the app again
- Navigate to Application menu -> About -> Latest Logging and provide me the first line of this logging that starts with "#0001 Configuration: Application started..."
- Switch OFF the "Developer options" in the settings

**Comment by G-R-O-U-C-H-O** [comment]
Hello,

Hmm - I watched the video. That is not the behaviour I have (!)

I am using MacBook Pro M1 ultra running Sequoia.

I would try the appon my older Intel Macs, but they are running High Sierra and cannot be upgraded any further.

The line you requested is: #0001 Configuration: Application started: 2.14.0, OS: macOS

(I reverted to the App Store version after trying the DMG version you linked to earlier).

By the way - the file sizes for music control.app were very different - 76.1MB DMG version, and 30.7MB App Store version.

**Comment by mkulesh** [comment]
Hi!

agree, it is strange... The same DMG has different behavior on different macs... There are only two differences between your and my systems that may be responsible for broken scrolling: Intel vs. M1 and Sonoma vs. Sequoia... 

In the application settings, do you have the item "Use USB-RI interface" in the "Advanced" parameter group?

Some years ago I tested the app on High Sierra. Previously it worked fine and I hope it still working. 

> By the way - the file sizes for music control.app were very different - 76.1MB DMG version, and 30.7MB App Store version.
I can explain it in the way that my build is generic and contains several binaries for different platforms while the build downloaded from App Store is optimized for your system and only contains code related to your platform. 30.7MB is exactly the correct size; my DMG shall contain both x86_64 and Apple Silicon binaries and therefore has double size.

**Comment by G-R-O-U-C-H-O** [comment]
Oops I forgot to reply to that question - Use USB-RI interface is set to ’None’.

Thank you for the file size difference explanation. Understood :-)

**Comment by mkulesh** [comment]
Thanks, 

> Oops I forgot to reply to that question - Use USB-RI interface is set to ’None’.

now I am sure that the app runs in macOS mode instead of iOS mode since this option is only available on desktop :) 

Broken scrolling in your case is related either to M1 or to Sequoia... I plan the upgrading to Sequoia in November and will be able to test the app at least on the newest macOS. Unfortunately I have no M1 or M2 device.

Please let me know how the app works on High Sierra.

**Comment by G-R-O-U-C-H-O** [comment]
I just downloaded and installed the app - Version 2.13.0 (306) on High Sierra on an Intel Mac - It works perfectly. (Mouse scrolling also).

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O,
I finally installed macOS 15 (Sequoia), updated XCode to the latest version and recompiled the app on Sequoia. As previously on macOS Sonoma, there is no problem with mouse wheel, it works as desired. Could you please download the latest build MusicControl-v2.14.1-macos.dmg from https://1drv.ms/f/s!At2sh2-YDyGFdsDFl6N3ncDowMg and test whether it now works on your laptop? By the way, I also fixed the size of DMG file :)

**Comment by G-R-O-U-C-H-O** [comment]
I dowloaded and installed 2.14.1 - no change in mouse scrolling behaviour :-(

Uninstalled completely, including plist files, reinstalled, app loaded in ‘virgin’ state, and still no change in scrolling behaviour.

**Comment by mkulesh** [comment]
Hi! Do you have any tools installed on your mac that tune or change the mouse behavior like fine-tuning of scrolling speed (for example "BetterMouse")?

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O,

I found a special configuration parameter related to the touchpad scrolling. I hope it should work now. Could you please manually install the latest macOS build MusicControl-v2.14.3-macos.dmg from here: https://1drv.ms/f/s!At2sh2-YDyGFdsDFl6N3ncDowMg and test how it now works for you?

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O 
the latest macOS has more strict security that may restrict to update or run an app downloaded from Internet. Please try following:
1. Uninstall previously installed version (Open Application and move Music Control to Bin). Your app settings will not be lost.
2. Open downloaded DMG file and drag Music Control to application.
3. Upon first start, macOS will block it. Open System Settings -> Privacy & Security -> Security and allow to run Music Control.
4. The latest macOS has also strange behavior related to the local network permissions. Open System Settings -> Privacy & Security -> Local network. Music Control should appear in the list with enabled network permission. However, the network may still blocked by macOS. Disable network permission and enable it again.
5. After it, the app should work.

**Comment by G-R-O-U-C-H-O** [comment]
OK,

I managed to copy the app from the dmg file to my downloads folder, and managed to run it.

The scrolling bug has indeed been eliminated, and scrolling works as expected :-)

I am still unable however, to move/copy the app to my applications folder.

I am given the following reason:

"The operation can’t be completed because some items had to be skipped. For each item, choose File > Get Info, make sure “Locked” is deselected, and then check the Sharing & Permissions section. When you are sure the items are unlocked and not designated as Read Only or No Access, try again."

**Comment by G-R-O-U-C-H-O** [comment]
OK, I also managed to copy to the applications folder.

All seems to be working as expected :-)

I’ll keep an eye out for the official publication of the update on the Appstore and then reinstall it from there.

Thank you!

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O, the new release 2.14.3 with this fix is now available on the store.

**Comment by G-R-O-U-C-H-O** [comment]
Thank you.

Installed on Mac and on iOS, and all works fine. :-)

By the way, since the last iOS/Mac updates, the album art is broken when using Airplay. (This is also broken in the official Onkyo app)

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O 

thank you for feedback. Unfortunately I am not able to reproduce the problem with the missing album art. I tried following setup:
1. on iPad, I run the Spotify app that plays a song and shows a corresponding album art
2. Spotify on iPad is streaming via Airplay on NS-6170 that has the Airplay input channel selected
3. on macOS: when I start the Music Control and connect to NS-6170, the same album art as in Spotify app is shown - works as desired
4. on other iPhone with the latest iOS version: when I start the Music Control and connect to NS-6170, the same album art as in Spotify app is shown - also works as desired:
<img width="781" alt="Image" src="https://github.com/user-attachments/assets/65ec44b2-a555-42b5-899b-b5b1927b79eb" />

However, when I use VLC on iPad and start any local mp3 - VLC itself does not show album art and, therefore, does not propagate it to the Onkyo player. But it is a problem in VLC...

Could you please describe your setup more precise in order to reproduce the problem?

**Comment by G-R-O-U-C-H-O** [comment]
Hello mkulesh. I should have been more precise. My mistake. This is only when using AirPlay to stream from the native music app on Mac OS and on iPhone and iPod os. I tried Spotify, and as you say, the art is displayed correctly. On 24 Apr 2025, at 20:16, Mikhail Kulesh ***@***.***> wrote:﻿
mkulesh left a comment (mkulesh/onpc#322)
Hi @G-R-O-U-C-H-O
thank you for feedback. Unfortunately I am not able to reproduce the problem with the missing album art. I tried following setup:

on iPad, I run the Spotify app that plays a song and shows a corresponding album art
Spotify on iPad is streaming via Airplay on NS-6170 that has the Airplay input channel selected
on macOS: when I start the Music Control and connect to NS-6170, the same album art as in Spotify app is shown - works as desired
on other iPhone with the latest iOS version: when I start the Music Control and connect to NS-6170, the same album art as in Spotify app is shown - also works as desired:

Screenshot.2025-04-24.at.20.15.09.png (view on web)
However, when I use VLC on iPad and start any local mp3 - VLC itself does not show album art and, therefore, does not propagate it to the Onkyo player. But it is a problem in VLC...
Could you please describe your setup more precise in order to reproduce the problem?

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O 
thank you for details. The problem is that the native Apple music app has some changes that are not more compatible with the old receiver firmware. I suggest to open an issue on the Apple support portal directly since it definitively an Apple bug or a new feature :)

**Comment by G-R-O-U-C-H-O** [comment]
Hahaha! Yes. Most definitely a new feature. 😂On 24 Apr 2025, at 20:50, Mikhail Kulesh ***@***.***> wrote:﻿
mkulesh left a comment (mkulesh/onpc#322)
Hi @G-R-O-U-C-H-O
thank you for details. The problem is that the native Apple music app has some changes that are not more compatible with the old receiver firmware. I suggest to open an issue on the Apple support portal directly since it definitively an Apple bug or a new feature :)

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O 
I now updated macOS to the latest version, imported some mp3 tracks into the Apple Music app, and stream it via Airplay to my Onkyo Player. The album art is shown and works as desired:

<img width="1540" alt="Image" src="https://github.com/user-attachments/assets/ca62cbbd-2e27-4a5c-b7fc-592feabe2cdd" />
Do you play a local mp3 or something from the internet?

**Comment by G-R-O-U-C-H-O** [comment]
Ok, here is what I found out.

Playback from iPad/iPhone, mp3 files has artwork displayed correctly. I, however use mostly m4a and those do not display any artwork.

Also, I just tested playback using Mac OS, and now it seems that both mp3 and m4a files have correct artwork being displayed 🤷‍♂️.

I don’t know if I imagined it ten times, or if something changed, but in my mind Mac OS was not displaying m4a files last time I checked (!) 🤔

**Comment by mkulesh** [comment]
Hi @G-R-O-U-C-H-O 
you can try to debug the problem with m4a as follows:
- Activate the "Developer options" in the app settings
- Wait until the album cover is missing
- Open App menu -> About -> Latest logging
- Search the latest line that contains "UrlLoader: loading data from URL: ..."
- Try to open the URL logged in this line in any browser. Can the browser open such an URL? If yes, please send me the app log on mikhail.kulesh@gmail.com

**Comment by G-R-O-U-C-H-O** [comment]
The browser does not find anything to load (http://10.0.1.81/album_art.cgi)

(Remember this is also not displaying on the official iOS Onkyo app)
